-- =========================================================
-- Demo seed data for the Final Task scenario:
-- Org A (with owner + editor + viewer) and Org B (isolated).
-- Assumes you've already signed up the corresponding auth.users via the
-- frontend (or nhost auth API) and have their user ids - substitute the
-- placeholder UUIDs below before running, or use the companion
-- seed-after-signup.sql generated by scripts/seed.ts.
-- =========================================================

insert into organizations (id, name, quota_calls_allowed, quota_calls_used)
values
  ('a0000000-0000-0000-0000-000000000001', 'Org A', 1000, 0),
  ('b0000000-0000-0000-0000-000000000002', 'Org B', 1000, 0);

-- Replace these user_id values with real auth.users ids after signing up:
--   orgA-owner@example.com, orgA-editor@example.com, orgA-viewer@example.com,
--   orgB-owner@example.com
--
 insert into org_members (org_id, user_id, role) values
   ('a0000000-0000-0000-0000-000000000001', '558a613d-c054-4834-941d-7e9e7c9576d4',  'owner'),
   ('a0000000-0000-0000-0000-000000000001', 'dce3376a-c533-4e85-8157-5403e8c7d503', 'editor'),
   ('a0000000-0000-0000-0000-000000000001', '667f2bf5-8c1b-4b11-bef3-ca62f42b7c53', 'viewer'),
   ('b0000000-0000-0000-0000-000000000002', 'a086b15d-9ed3-462e-bdcd-356f4913a904',  'owner');
