drop trigger if exists trg_workflows_touch on workflows;
drop function if exists fn_touch_updated_at();
drop function if exists fn_user_role_in_org(uuid, uuid);
drop view if exists org_usage_stats;
drop table if exists step_runs;
drop table if exists workflow_runs;
drop table if exists workflow_triggers;
drop table if exists workflow_steps;
drop table if exists workflows;
drop table if exists org_members;
drop table if exists organizations;
drop type if exists step_run_status;
drop type if exists run_status;
drop type if exists trigger_type;
drop type if exists step_type;
drop type if exists org_role;
